Ensayo sin local 5000

diff --git a/.github/workflows/daily_inference.yml b/.github/workflows/daily_inference.yml
--- a/.github/workflows/daily_inference.yml
+++ b/.github/workflows/daily_inference.yml
@@ -10,24 +10,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: 📥 Clonar repositorio
+    - name: Clonar repositorio
       uses: actions/checkout@v3
 
-    - name: 🐍 Instalar Python
+    - name: Instalar Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
 
-    - name: 📦 Instalar dependencias
+    - name: Instalar dependencias
       run: |
         python -m pip install --upgrade pip
         pip install yfinance pandas numpy scikit-learn matplotlib mlflow
 
-    - name: 🔮 Ejecutar script
+    - name: Ejecutar script
       run: |
-        python daily_forecast.py || { echo "❌ Error al ejecutar el script"; exit 1; }
+        python daily_forecast.py || { echo "Error al ejecutar el script"; exit 1; }
 
-    - name: 📤 Subir resultados al repositorio
+    - name: Subir resultados al repositorio
       run: |
         git config --global user.name "github-actions"
         git config --global user.email "actions@github.com"
